{% set version = "2.0.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-httpgd
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/httpgd_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/httpgd/httpgd_{{ version }}.tar.gz
  sha256: 4f2764ebc1b29a70dcb4a2a1ed4b054713a0436fabce80162766fa9e144aec78

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-asioheaders >=1.22.1       # [build_platform != target_platform]
    - r-cpp11 >=0.2.4              # [build_platform != target_platform]
    - r-unigd                      # [build_platform != target_platform]
  host:
    - r-base
    - r-asioheaders >=1.22.1
    - r-cpp11 >=0.2.4
    - r-unigd
  run:
    - r-base
    - r-cpp11 >=0.2.4
    - r-unigd

test:
  commands:
    - $R -e "library('httpgd')"           # [not win]
    - "\"%R%\" -e \"library('httpgd')\""  # [win]

about:
  home: https://nx10.github.io/httpgd/
  dev_url: https://github.com/nx10/httpgd
  license: GPL-2.0-or-later
  summary: A graphics device for R that is accessible via network protocols. This package was created to make it easier to embed live R graphics in integrated development environments and other applications. The included 'HTML/JavaScript' client (plot viewer) aims to provide a better overall user experience when dealing
    with R graphics. The device asynchronously serves graphics via 'HTTP' and 'WebSockets'.
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["SRC_DIR"] }}/inst/licenses/belle-MIT.txt
    - {{ environ["SRC_DIR"] }}/inst/licenses/CrowCpp-BSD-3-Clause.txt
    - {{ environ["SRC_DIR"] }}/inst/licenses/material-design-icons-Apache-2-0.txt

extra:
  recipe-maintainers:
    - conda-forge/r
    - nsandau
